-- data.sql gets loaded in H2 DB, when server starts
-- table will be created by 'SchemaUpdate' triggered by SpringBoot auto configuration.
/*
CREATE TABLE PERSON (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255),
    DOB TIMESTAMP,
    PRIMARY KEY(ID)
);
*/
INSERT INTO PERSON(ID,NAME,LOCATION,DOB) VALUES(101,'JACK','NY',SYSDATE());
INSERT INTO PERSON(ID,NAME,LOCATION,DOB) VALUES(102,'ROSE','NY',SYSDATE());
INSERT INTO PERSON(ID,NAME,LOCATION,DOB) VALUES(103,'DOW','NL',SYSDATE());
INSERT INTO PERSON(ID,NAME,LOCATION,DOB) VALUES(104,'JASMINE','NL',SYSDATE());
INSERT INTO PERSON(ID,NAME,LOCATION,DOB) VALUES(105,'JHON','DM',SYSDATE());

-- OneToOne Mapping
INSERT INTO COURSE(ID,NAME,CREATED_DATE,LAST_UPDATED_DATE) VALUES(1001,'JACK',SYSDATE(),SYSDATE());
INSERT INTO COURSE(ID,NAME,CREATED_DATE,LAST_UPDATED_DATE) VALUES(1002,'JACK',SYSDATE(),SYSDATE());
INSERT INTO COURSE(ID,NAME,CREATED_DATE,LAST_UPDATED_DATE) VALUES(1001,'JACK',SYSDATE(),SYSDATE());
INSERT INTO COURSE(ID,NAME,CREATED_DATE,LAST_UPDATED_DATE) VALUES(1001,'JACK',SYSDATE(),SYSDATE());